version: "3.9"
services:
  app:
      container_name: vite-app
      build:
          context: .
          dockerfile: Dockerfile
      ports:
          - '8000:8000'
      environment:
          TZ: 'Asia/Kuala_Lumpur'
      volumes:
        - .:/app
        - /app/node_modules

  test-db:
    image: postgres
    restart: always
    container_name: test-web-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example-password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres: